// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Thay thế các giá trị dưới đây bằng config từ Firebase Console

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9YG0SsVNOOX-zJg8Xii6LSolTAVPyeY',
    appId: '1:682216970253:web:f75b582c9488b50a5a9d44',
    messagingSenderId: '682216970253',
    projectId: 'login-d2d6a',
    authDomain: 'login-d2d6a.firebaseapp.com',
    storageBucket: 'login-d2d6a.firebasestorage.app',
    measurementId: 'G-7YDEHV6Q66',
  );

  // Vào Firebase Console > Project Settings > Your apps > Web app

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vbs69Xy_ccwDK-eFxNbl2xYgPTNzQxo',
    appId: '1:682216970253:android:dfc3cf07628c49ef5a9d44',
    messagingSenderId: '682216970253',
    projectId: 'login-d2d6a',
    storageBucket: 'login-d2d6a.firebasestorage.app',
  );

  // TODO: Thay thế các giá trị Android nếu bạn đã có google-services.json

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQWaskD33uZr9VrQ5aMmf6jFZ8U5EE6g',
    appId: '1:682216970253:ios:e6ddf04a088d198b5a9d44',
    messagingSenderId: '682216970253',
    projectId: 'login-d2d6a',
    storageBucket: 'login-d2d6a.firebasestorage.app',
    iosBundleId: 'com.example.flWeek01',
  );

  // TODO: Thay thế các giá trị iOS nếu bạn đã có GoogleService-Info.plist

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQWaskD33uZr9VrQ5aMmf6jFZ8U5EE6g',
    appId: '1:682216970253:ios:e6ddf04a088d198b5a9d44',
    messagingSenderId: '682216970253',
    projectId: 'login-d2d6a',
    storageBucket: 'login-d2d6a.firebasestorage.app',
    iosBundleId: 'com.example.flWeek01',
  );

  // macOS config (tùy chọn)

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI9YG0SsVNOOX-zJg8Xii6LSolTAVPyeY',
    appId: '1:682216970253:web:16edaacddebefbb45a9d44',
    messagingSenderId: '682216970253',
    projectId: 'login-d2d6a',
    authDomain: 'login-d2d6a.firebaseapp.com',
    storageBucket: 'login-d2d6a.firebasestorage.app',
    measurementId: 'G-PRYD4XKQFC',
  );

}